services:
    - type: web
    name: sigpy
    env: python
    plan: free
    branch: master
    buildCommand: pip install.
    startCommand: python app.py
    envVars:
            - key: PYTHON_VERSION
        value: 3.11.0